/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-primary-container": "#dad7ff",
          "primary-fixed-dim": "#c3c0ff",
          "surface-bright": "#39393b",
          "on-primary-fixed": "#0f0069",
          "inverse-surface": "#e5e1e4",
          "primary": "#c3c0ff",
          "on-tertiary-container": "#ebd2ff",
          "on-secondary-container": "#00344e",
          "on-tertiary-fixed": "#2c0051",
          "inverse-primary": "#4d44e3",
          "on-tertiary": "#490080",
          "tertiary-fixed": "#f0dbff",
          "secondary-fixed-dim": "#89ceff",
          "surface": "#131315",
          "on-error": "#690005",
          "primary-container": "#4f46e5",
          "surface-variant": "#353437",
          "error": "#ffb4ab",
          "on-tertiary-fixed-variant": "#6900b3",
          "on-background": "#e5e1e4",
          "surface-tint": "#c3c0ff",
          "on-secondary-fixed": "#001e2f",
          "surface-container-low": "#1b1b1d",
          "outline": "#918fa1",
          "inverse-on-surface": "#303032",
          "secondary-fixed": "#c9e6ff",
          "secondary": "#89ceff",
          "on-primary": "#1d00a5",
          "primary-fixed": "#e2dfff",
          "on-surface-variant": "#c7c4d8",
          "on-error-container": "#ffdad6",
          "surface-dim": "#131315",
          "on-secondary": "#00344d",
          "on-surface": "#e5e1e4",
          "surface-container-highest": "#353437",
          "surface-container-high": "#2a2a2c",
          "outline-variant": "#464555",
          "on-primary-fixed-variant": "#3323cc",
          "background": "#131315",
          "tertiary-container": "#862dd4",
          "on-secondary-fixed-variant": "#004c6e",
          "error-container": "#93000a",
          "surface-container-lowest": "#0e0e10",
          "tertiary": "#ddb7ff",
          "secondary-container": "#00a2e6",
          "surface-container": "#201f21",
          "tertiary-fixed-dim": "#ddb7ff"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "sm": "12px",
          "gutter": "24px",
          "container-max": "1280px",
          "md": "24px",
          "base": "8px",
          "xs": "4px",
          "xl": "80px",
          "lg": "48px"
      },
      "fontFamily": {
          "headline-xl": ["Plus Jakarta Sans"],
          "label-md": ["Inter"],
          "display-lg": ["Plus Jakarta Sans"],
          "headline-lg-mobile": ["Plus Jakarta Sans"],
          "headline-lg": ["Plus Jakarta Sans"],
          "label-sm": ["Inter"],
          "body-lg": ["Inter"],
          "body-md": ["Inter"]
      },
      "fontSize": {
          "headline-xl": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600"}],
          "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
          "headline-lg": ["28px", {"lineHeight": "1.3", "fontWeight": "600"}],
          "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}],
          "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
